(()=>{
'use strict';
const esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
const S={items:[],channels:[],episodes:[],selectedChannel:'',from:'',to:'',search:'',dragId:null};
const $=id=>document.getElementById(id);
const toast=(m,bad=false)=>{let x=$('ssMsg');if(!x)return;x.textContent=m;x.className='msg';x.style.display='block';x.style.borderColor=bad?'#703044':'#246c49';setTimeout(()=>x.style.display='none',3500)};
const fmt=d=>d?new Date(d).toLocaleString([],{month:'short',day:'numeric',year:'numeric',hour:'numeric',minute:'2-digit'}):'—';
const isoLocal=d=>{if(!d)return '';let x=new Date(d);x.setMinutes(x.getMinutes()-x.getTimezoneOffset());return x.toISOString().slice(0,16)};
const duration=s=>{s=Number(s||0);if(!s)return 'Auto';let m=Math.floor(s/60),sec=s%60;return `${m}m${sec?` ${sec}s`:''}`};
async function load(){
 try{
  const ch=await db.from('tv_channels').select('id,name,slug').order('sort_order',{ascending:true}); if(ch.error)throw ch.error; S.channels=ch.data||[];
  const ep=await db.from('episodes').select('id,show_id,title,season_number,episode_number,duration_seconds,youtube_url,video_url,thumbnail_url,status').order('sort_order',{ascending:true}).limit(1000); if(ep.error)throw ep.error; S.episodes=ep.data||[];
  await render();
 }catch(e){$('scheduleStudioBody').innerHTML=`<div class="notice"><span class="bad">${esc(e.message||e)}</span></div>`}
}
async function loadItems(){
 let q=db.from('schedule_items').select('id,channel_id,show_id,episode_id,title,description,starts_at,ends_at,item_type,status,is_active,schedule_source,duration_seconds,video_url,video_type,youtube_url,sort_order,thumbnail_url,start_time,end_time').order('starts_at',{ascending:true}).order('sort_order',{ascending:true}).limit(2000);
 if(S.selectedChannel)q=q.eq('channel_id',S.selectedChannel);
 if(S.from)q=q.gte('starts_at',new Date(S.from+'T00:00:00').toISOString());
 if(S.to)q=q.lt('starts_at',new Date(S.to+'T23:59:59').toISOString());
 const r=await q;if(r.error)throw r.error;S.items=r.data||[];
}
function channelName(id){return S.channels.find(x=>x.id===id)?.name||'Unassigned'}
function epFor(id){return S.episodes.find(x=>x.id===id)}
function renderShell(){
 const p=$('page-schedule');if(!p)return;
 p.innerHTML=`<div class="hero"><div><h1>📺 Schedule Studio</h1><p class="muted">Build and maintain the CrowRules TV schedule from the canonical <b>schedule_items</b> table.</p></div><div class="actions"><button id="ssRefresh">↻ Refresh</button><button class="primary" id="ssAdd">+ Add Program</button></div></div><div id="scheduleStudioBody"><div class="toolbar"><select id="ssChannel" class="grow"><option value="">All TV channels</option>${S.channels.map(c=>`<option value="${esc(c.id)}">${esc(c.name)}</option>`).join('')}</select><input id="ssFrom" type="date"><input id="ssTo" type="date"><input id="ssSearch" class="grow" placeholder="Search schedule…"><button id="ssToday">Today</button><button id="ssClear">Clear</button></div><div id="ssMsg" class="msg" style="display:none"></div><div id="ssStats" class="grid"></div><div class="card" style="margin-top:14px"><div class="hero"><div><h2>Programming Timeline</h2><p class="muted">Drag items to reorder. Edit times to build a continuous schedule.</p></div><button id="ssFillGaps">Auto-fill selected channel</button></div><div id="ssList" class="list"></div></div></div>`;
 $('ssChannel').value=S.selectedChannel;$('ssFrom').value=S.from;$('ssTo').value=S.to;$('ssSearch').value=S.search;
 $('ssChannel').onchange=()=>{S.selectedChannel=$('ssChannel').value;refreshItems()};$('ssFrom').onchange=()=>{S.from=$('ssFrom').value;refreshItems()};$('ssTo').onchange=()=>{S.to=$('ssTo').value;refreshItems()};$('ssSearch').oninput=e=>{S.search=e.target.value;drawList()};$('ssToday').onclick=()=>{let d=new Date().toISOString().slice(0,10);S.from=d;S.to=d;$('ssFrom').value=d;$('ssTo').value=d;refreshItems()};$('ssClear').onclick=()=>{S.from=S.to=S.search='';$('ssFrom').value='';$('ssTo').value='';$('ssSearch').value='';refreshItems()};$('ssRefresh').onclick=refreshItems;$('ssAdd').onclick=()=>openEditor();$('ssFillGaps').onclick=fillGaps;
}
async function render(){renderShell();await refreshItems()}
async function refreshItems(){try{await loadItems();drawStats();drawList()}catch(e){toast(e.message||e,true)}}
function drawStats(){let live=S.items.filter(x=>x.item_type==='live').length,pub=S.items.filter(x=>x.status==='published').length,active=S.items.filter(x=>x.is_active!==false).length;$('ssStats').innerHTML=[['Items',S.items.length],['Active',active],['Published',pub],['Live Events',live]].map(x=>`<div class="card"><div class="muted">${x[0]}</div><b style="font-size:25px">${x[1]}</b></div>`).join('')}
function drawList(){
 const term=S.search.toLowerCase();let a=S.items.filter(x=>!term||[x.title,channelName(x.channel_id),x.item_type,x.status].join(' ').toLowerCase().includes(term));
 if(!a.length){$('ssList').innerHTML='<div class="notice muted">No schedule items match these filters.</div>';return}
 $('ssList').innerHTML=a.map((x,i)=>{let e=epFor(x.episode_id);return `<div class="row" draggable="true" data-id="${x.id}" style="grid-template-columns:55px 1fr auto"><div><span class="pill">${i+1}</span><div class="muted" style="margin-top:5px">☷ drag</div></div><div><div><b>${esc(x.title||e?.title||'Untitled')}</b> ${x.item_type==='live'?'<span class="badge">🔴 LIVE</span>':''}</div><div class="muted">${fmt(x.starts_at)} → ${fmt(x.ends_at)} · ${duration(x.duration_seconds)} · ${esc(channelName(x.channel_id))}</div><div style="margin-top:5px"><span class="badge">${esc(x.item_type||'episode')}</span><span class="badge">${esc(x.status||'scheduled')}</span>${e?`<span class="badge">S${esc(e.season_number??'—')} E${esc(e.episode_number??'—')}</span>`:''}</div></div><div class="actions"><button data-edit="${x.id}">Edit</button><button data-copy="${x.id}">Duplicate</button><button data-del="${x.id}" class="danger">Delete</button></div></div>`}).join('');
 $('ssList').querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>openEditor(S.items.find(x=>x.id===b.dataset.edit)));$('ssList').querySelectorAll('[data-copy]').forEach(b=>b.onclick=()=>duplicate(S.items.find(x=>x.id===b.dataset.copy)));$('ssList').querySelectorAll('[data-del]').forEach(b=>b.onclick=()=>remove(S.items.find(x=>x.id===b.dataset.del)));
 $('ssList').querySelectorAll('.row').forEach(r=>{r.ondragstart=()=>S.dragId=r.dataset.id;r.ondragover=e=>e.preventDefault();r.ondrop=async()=>{if(S.dragId&&S.dragId!==r.dataset.id)await move(S.dragId,r.dataset.id)}})
}
function editorHtml(x){let isEdit=!!x, e=epFor(x?.episode_id), now=isoLocal(x?.starts_at||new Date()), end=isoLocal(x?.ends_at||new Date(Date.now()+Number(x?.duration_seconds||e?.duration_seconds||1800)*1000));return `<div class="formgrid"><div class="field"><label>TV Channel</label><select id="se_channel"><option value="">Unassigned</option>${S.channels.map(c=>`<option value="${esc(c.id)}" ${x?.channel_id===c.id?'selected':''}>${esc(c.name)}</option>`).join('')}</select></div><div class="field"><label>Program Type</label><select id="se_type"><option ${(!x||x.item_type==='episode')?'selected':''}>episode</option><option ${x?.item_type==='rerun'?'selected':''}>rerun</option><option ${x?.item_type==='special'?'selected':''}>special</option><option ${x?.item_type==='movie'?'selected':''}>movie</option><option ${x?.item_type==='intermission'?'selected':''}>intermission</option><option ${x?.item_type==='live'?'selected':''}>live</option></select></div><div class="field" style="grid-column:1/-1"><label>Episode (optional)</label><select id="se_episode"><option value="">Manual / non-episode program</option>${S.episodes.map(q=>`<option value="${esc(q.id)}" ${x?.episode_id===q.id?'selected':''}>${esc(q.title)} — S${esc(q.season_number??'—')} E${esc(q.episode_number??'—')} (${duration(q.duration_seconds)})</option>`).join('')}</select></div><div class="field"><label>Start</label><input id="se_start" type="datetime-local" value="${now}"></div><div class="field"><label>End</label><input id="se_end" type="datetime-local" value="${end}"></div><div class="field"><label>Duration seconds</label><input id="se_duration" type="number" min="1" value="${esc(x?.duration_seconds||e?.duration_seconds||1800)}"></div><div class="field"><label>Status</label><select id="se_status"><option>scheduled</option><option>published</option><option>cancelled</option></select></div><div class="field"><label>Title</label><input id="se_title" value="${esc(x?.title||e?.title||'')}"></div><div class="field"><label>YouTube URL</label><input id="se_youtube" value="${esc(x?.youtube_url||e?.youtube_url||'')}"></div><div class="field"><label>Video URL</label><input id="se_video" value="${esc(x?.video_url||e?.video_url||'')}"></div><div class="field"><label>Thumbnail URL</label><input id="se_thumb" value="${esc(x?.thumbnail_url||e?.thumbnail_url||'')}"></div><div class="field"><label>Sort order</label><input id="se_sort" type="number" value="${esc(x?.sort_order??0)}"></div><div class="field"><label><input id="se_active" type="checkbox" ${x?.is_active!==false?'checked':''}> Active</label></div></div><p class="muted">Selecting an episode automatically supplies its title, video/YouTube URL and duration. End time is recalculated when duration changes.</p>`}
function openEditor(x){$('modalTitle').textContent=x?'Edit Schedule Item':'Add Schedule Item';$('form').innerHTML=editorHtml(x);$('modalMsg').classList.add('hidden');$('deleteBtn').classList.toggle('hidden',!x);$('modal').classList.remove('hidden');$('deleteBtn').onclick=()=>remove(x);$('saveBtn').onclick=()=>saveEditor(x);let sync=()=>{let e=epFor($('se_episode').value),d=Number($('se_duration').value||e?.duration_seconds||0),s=$('se_start').value;if(e){$('se_title').value=e.title||'';$('se_youtube').value=e.youtube_url||'';$('se_video').value=e.video_url||'';$('se_thumb').value=e.thumbnail_url||'';if(e.duration_seconds)$('se_duration').value=e.duration_seconds}if(s&&d){let z=new Date(s);z.setSeconds(z.getSeconds()+d);$('se_end').value=isoLocal(z)}};$('se_episode').onchange=sync;$('se_duration').oninput=()=>{let s=$('se_start').value,d=Number($('se_duration').value||0);if(s&&d){let z=new Date(s);z.setSeconds(z.getSeconds()+d);$('se_end').value=isoLocal(z)}}}
function close(){ $('modal').classList.add('hidden') }
window.closeModal=close;
async function saveEditor(x){try{let d={channel_id:$('se_channel').value||null,episode_id:$('se_episode').value||null,item_type:$('se_type').value,status:$('se_status').value,title:$('se_title').value.trim(),starts_at:new Date($('se_start').value).toISOString(),ends_at:new Date($('se_end').value).toISOString(),duration_seconds:Number($('se_duration').value)||null,youtube_url:$('se_youtube').value.trim()||null,video_url:$('se_video').value.trim()||null,thumbnail_url:$('se_thumb').value.trim()||null,sort_order:Number($('se_sort').value)||0,is_active:$('se_active').checked,schedule_source:'admin_studio',updated_at:new Date().toISOString()};if(!d.title)throw Error('Title is required.');if(x){let r=await db.from('schedule_items').update(d).eq('id',x.id);if(r.error)throw r.error}else{let r=await db.from('schedule_items').insert(d);if(r.error)throw r.error}close();await refreshItems();toast(x?'Schedule item updated.':'Schedule item created.')}catch(e){$('modalMsg').textContent=e.message||e;$('modalMsg').classList.remove('hidden')}}
async function remove(x){if(!x||!confirm(`Delete “${x.title||'this schedule item'}”?`))return;try{let r=await db.from('schedule_items').delete().eq('id',x.id);if(r.error)throw r.error;await refreshItems();toast('Schedule item deleted.')}catch(e){toast(e.message||e,true)}}
async function duplicate(x){try{let d={...x};delete d.id;delete d.created_at;d.title=(x.title||'Program')+' (Copy)';d.sort_order=Number(x.sort_order||0)+1;d.schedule_source='admin_studio';let r=await db.from('schedule_items').insert(d);if(r.error)throw r.error;await refreshItems();toast('Schedule item duplicated.')}catch(e){toast(e.message||e,true)}}
async function move(a,b){try{let A=S.items.find(x=>x.id===a),B=S.items.find(x=>x.id===b);if(!A||!B)return;let r=await db.from('schedule_items').update({sort_order:Number(B.sort_order||0)}).eq('id',A.id);if(r.error)throw r.error;r=await db.from('schedule_items').update({sort_order:Number(A.sort_order||0)}).eq('id',B.id);if(r.error)throw r.error;await refreshItems();toast('Order updated.')}catch(e){toast(e.message||e,true)}}
async function fillGaps(){if(!S.selectedChannel){toast('Choose a TV channel first.',true);return}let a=S.items.slice().sort((x,y)=>new Date(x.starts_at)-new Date(y.starts_at));if(!a.length){toast('No schedule items for this channel.',true);return}let cursor=new Date(a[0].starts_at);for(const x of a){let dur=Number(x.duration_seconds||0);if(!dur){let e=epFor(x.episode_id);dur=Number(e?.duration_seconds||0)}if(!dur)continue;let start=new Date(cursor),end=new Date(start);end.setSeconds(end.getSeconds()+dur);let r=await db.from('schedule_items').update({starts_at:start.toISOString(),ends_at:end.toISOString(),start_time:start.toISOString(),end_time:end.toISOString()}).eq('id',x.id);if(r.error){toast(r.error.message,true);return}cursor=end}await refreshItems();toast('Channel schedule times recalculated from the first item.')}
window.scheduleStudio={load};
const init=()=>{if(window.__scheduleStudioInit)return;window.__scheduleStudioInit=true;load()};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
