(()=>{"use strict";
const S={all:[],q:"",filter:"ALL",recent:JSON.parse(localStorage.getItem("crplus_recent_searches")||"[]")};
const filters=[["ALL","All"],["movie","Movies"],["series","Series"],["sports","Sports"],["podcast","Podcasts"],["dreamscapes","Dreamscapes"]];
const $=id=>document.getElementById(id), norm=v=>String(v??"").toLowerCase(), esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
const text=c=>[c.title,c.description,c.slug,c.content_type,c.division_key,...(c.tags||[])].map(norm).join(" ");
function filter(c){if(S.filter==="ALL")return true;let t=norm(c.content_type),d=norm(c.division_key);if(S.filter==="sports")return t.includes("sport")||d.includes("sport");if(S.filter==="podcast")return t.includes("podcast")||d.includes("podcast");if(S.filter==="dreamscapes")return t.includes("dream")||d.includes("dream");return t.includes(S.filter)}
function score(c){let q=norm(S.q).trim(),t=norm(c.title),d=norm(c.division_key);if(!q)return c.is_featured?10:0;let n=0;if(t===q)n+=100;if(t.startsWith(q))n+=50;if(t.includes(q))n+=30;if(d.includes(q))n+=18;if((c.tags||[]).some(x=>norm(x).includes(q)))n+=15;if(norm(c.description).includes(q))n+=8;return n}
function saveRecent(q){if(!q)return;S.recent=[q,...S.recent.filter(x=>x.toLowerCase()!==q.toLowerCase())].slice(0,8);localStorage.setItem("crplus_recent_searches",JSON.stringify(S.recent));renderRecent()}
function renderRecent(){let sec=$("recentSection"),box=$("recent");if(!S.recent.length){sec.classList.add("hidden");return}sec.classList.remove("hidden");box.innerHTML=S.recent.map(x=>'<div class="mini" data-recent="'+esc(x)+'"><strong>⌕ '+esc(x)+'</strong><small>Search again</small></div>').join("");box.querySelectorAll("[data-recent]").forEach(x=>x.onclick=()=>{S.q=x.dataset.recent;$("q").value=S.q;runSearch(true)})}
function renderTrending(){let arr=S.all.filter(x=>x.is_featured).slice(0,10);if(!arr.length)arr=S.all.slice(0,10);$("trending").innerHTML=arr.map(x=>'<div class="mini" data-slug="'+esc(x.slug)+'"><strong>'+esc(x.title)+'</strong><small>'+esc(x.division_key||x.content_type||"CrowRules+")+'</small></div>').join("");$("trending").querySelectorAll("[data-slug]").forEach(x=>x.onclick=()=>location.href="show.html?slug="+encodeURIComponent(x.dataset.slug))}
function renderChips(){let c=$("chips");c.innerHTML=filters.map(([v,l])=>'<button type="button" class="chip '+(v==="ALL"?"active":"")+'" data-filter="'+v+'">'+l+"</button>").join("");c.querySelectorAll(".chip").forEach(b=>b.onclick=()=>{S.filter=b.dataset.filter;c.querySelectorAll(".chip").forEach(x=>x.classList.toggle("active",x===b));runSearch(false)})}
function render(){let items=S.all.filter(filter),q=norm(S.q.trim());if(q)items=items.filter(x=>text(x).includes(q));items.sort((a,b)=>score(b)-score(a)||new Date(b.release_at||0)-new Date(a.release_at||0));$("resultTitle").textContent=q?'Results for "'+S.q.trim()+'"':"All Results";$("status").textContent=items.length+" titles";$("results").innerHTML=items.length?items.slice(0,100).map(c=>'<article class="card" data-slug="'+esc(c.slug)+'"><div class="poster">'+(c.thumbnail_url?'<img loading="lazy" src="'+esc(c.thumbnail_url)+'" alt="">':"")+'</div><div class="body"><div class="title">'+esc(c.title)+'</div><div class="meta">'+esc(c.content_type||"CONTENT")+(c.division_key?" · "+esc(c.division_key):"")+'</div><div class="desc">'+esc(c.description||"")+'</div></div></article>').join(""):'<div class="empty"><h2>No results found</h2><p>Try another title, keyword, division or genre.</p></div>';$("results").querySelectorAll("[data-slug]").forEach(x=>x.onclick=()=>location.href="show.html?slug="+encodeURIComponent(x.dataset.slug))}
function suggestions(){let q=norm($("q").value.trim()),box=$("suggestions");if(!q){box.classList.add("hidden");return}let hits=S.all.filter(x=>text(x).includes(q)).sort((a,b)=>score(b)-score(a)).slice(0,6);box.innerHTML=hits.map(x=>'<button type="button" data-suggest="'+esc(x.title)+'">'+esc(x.title)+'</button>').join("");box.classList.toggle("hidden",!hits.length);box.querySelectorAll("[data-suggest]").forEach(b=>b.onclick=()=>{$("q").value=b.dataset.suggest;S.q=b.dataset.suggest;box.classList.add("hidden");runSearch(true)})}
function runSearch(commit){S.q=$("q").value.trim();if(commit){history.replaceState(null,"","search.html"+(S.q?"?q="+encodeURIComponent(S.q):""));saveRecent(S.q)}render()}
async function load(){let r=await supabase.from("crplus_content").select("id,title,slug,description,thumbnail_url,backdrop_url,content_type,division_key,release_at,is_featured,age_rating,tags,duration_seconds,season_number,episode_number,show_id").eq("is_published",true).order("release_at",{ascending:false}).limit(500);if(r.error){$("status").textContent="Search unavailable";console.error(r.error);return}S.all=r.data||[];$("status").textContent=S.all.length+" titles";renderTrending();render()}
document.addEventListener("DOMContentLoaded",()=>{renderChips();renderRecent();let p=new URLSearchParams(location.search);$("q").value=p.get("q")||"";S.q=$("q").value;load();$("q").addEventListener("input",suggestions);$("searchForm").onsubmit=e=>{e.preventDefault();runSearch(true)};$("clearRecent").onclick=()=>{S.recent=[];localStorage.removeItem("crplus_recent_searches");renderRecent()};document.addEventListener("click",e=>{if(!e.target.closest(".searchbox"))$("suggestions").classList.add("hidden")})});
})();