const SUPABASE_URL="https://cevylpnoexugwgygvtgu.supabase.co";
const SUPABASE_KEY="sb_publishable_AdfM5y6RqvF3tbvEVzDZSg_JuGTQLD-";
const sb=supabase.createClient(SUPABASE_URL,SUPABASE_KEY);
let catalog=[];
const $=s=>document.querySelector(s);
const esc=v=>String(v??"").replace(/[&<>"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]));
function card(c){const live=c.playback_type==="youtube_live"||c.content_type==="live";return '<article class="card"><div class="poster">'+esc(c.title)+'</div><div class="cardBody"><h3>'+esc(c.title)+'</h3><div class="muted">'+esc(c.content_type)+' · '+esc(c.division_key||"CrowRules+")+(live?' · 🔴 LIVE':'')+'</div><div class="cardActions"><a class="btn mini primary" href="title.html?id='+encodeURIComponent(c.id)+'">View</a><button class="btn mini" data-list="'+c.id+'">＋ List</button></div></div></article>'}
async function load(){const{data,error}=await sb.from("crplus_content").select("*").eq("is_published",true).order("is_featured",{ascending:false}).order("release_at",{ascending:false,nullsFirst:false});if(error){console.error(error);return}catalog=data||[];$("#featured")&&($("#featured").innerHTML=catalog.map(card).join("")||'<p class="muted">No published titles yet.</p>');bindList();await loadUser();await loadPlans();await loadLive();loadCollections()}
async function loadLive(){const{data}=await sb.from("crplus_live_channels").select("*").eq("is_live",true).order("sort_order");const g=$("#liveGrid");if(!g)return;g.innerHTML=(data||[]).map(x=>'<div class="liveCard"><span class="liveBadge">● LIVE</span><h2>'+esc(x.name)+'</h2><p>'+esc(x.description||"Live on CrowRules+")+'</p><a class="btn primary" href="live.html?id='+x.id+'">Watch Live</a></div>').join("")||'<div class="callout"><h2>No live channels right now.</h2><p>Scheduled CrowRules+ live programming will appear here.</p></div>'}
async function loadUser(){const{data:{user}}=await sb.auth.getUser();if(!user){$("#accountStatus")&&($("#accountStatus").textContent="Sign in to sync your list, history, ratings and Universal Membership.");$("#signIn")&&($("#signIn").hidden=false);$("#signOut")&&($("#signOut").hidden=true);return}$("#accountStatus")&&($("#accountStatus").textContent=user.email);$("#signIn")&&($("#signIn").hidden=true);$("#signOut")&&($("#signOut").hidden=false);const{data}=await sb.from("crplus_watch_history").select("*,crplus_content(*)").eq("user_id",user.id).order("last_watched_at",{ascending:false}).limit(8);const c=$("#continue");if(c)c.innerHTML=(data||[]).map(x=>x.crplus_content?card(x.crplus_content):"").join("")||'<p class="muted">Nothing here yet.</p>';const{data:list}=await sb.from("crplus_my_list").select("*,crplus_content(*)").eq("user_id",user.id).order("created_at",{ascending:false}).limit(8);const l=$("#myList");if(l)l.innerHTML=(list||[]).map(x=>x.crplus_content?card(x.crplus_content):"").join("")||'<p class="muted">Your list is empty.</p>'}
function bindList(){document.querySelectorAll("[data-list]").forEach(b=>b.onclick=async()=>{const{data:{user}}=await sb.auth.getUser();if(!user){$("#authDialog")?.showModal();return}const{error}=await sb.from("crplus_my_list").upsert({user_id:user.id,content_id:b.dataset.list});b.textContent=error?"＋ List":"✓ Saved"})}
async function loadPlans(){const p=$("#plans");if(!p)return;const{data}=await sb.from("membership_plans").select("*").eq("is_active",true).order("sort_order");p.innerHTML=(data||[]).map(x=>'<div class="plan '+(x.is_featured?"featured":"")+'"><h2>'+esc(x.name)+'</h2><h3>$'+((x.price_cents||0)/100).toFixed(2)+' / '+esc(x.billing_interval||"month")+'</h3><p class="muted">'+esc(x.description||"Universal CrowRules membership.")+'</p><button class="btn primary" data-plan="'+x.id+'">Choose Plan</button></div>').join("")||'<p class="muted">Membership plans will appear here.</p>';document.querySelectorAll("[data-plan]").forEach(b=>b.onclick=()=>checkout(b.dataset.plan))}
async function checkout(plan){const{data:{session}}=await sb.auth.getSession();if(!session){$("#authDialog")?.showModal();return}const{data,error}=await sb.functions.invoke("membership-checkout",{body:{plan_id:plan,return_url:location.href}});if(error){alert(error.message);return}if(data?.url)location.href=data.url}
async function loadCollections(){const{data:cols}=await sb.from("crplus_collections").select("*,crplus_collection_items(content_id,sort_order)").eq("is_published",true).order("title");const target=$("#collections");if(!target)return;target.innerHTML=(cols||[]).map(col=>'<div class="collection"><h2>'+esc(col.title)+'</h2><p class="muted">'+esc(col.description||"")+'</p><div class="cards">'+(col.crplus_collection_items||[]).sort((a,b)=>a.sort_order-b.sort_order).map(i=>{const c=catalog.find(x=>x.id===i.content_id);return c?card(c):""}).join("")+'</div></div>').join("")||'<p class="muted">Curated collections will appear here.</p>'}
$("#signIn")&&($("#signIn").onclick=()=>$("#authDialog")?.showModal());$("#signOut")&&($("#signOut").onclick=async()=>{await sb.auth.signOut();location.reload()});$("#closeAuth")&&($("#closeAuth").onclick=()=>$("#authDialog")?.close());$("#closeSearch")&&($("#closeSearch").onclick=()=>$("#searchDialog")?.close());$("#emailAuth")&&($("#emailAuth").onclick=async e=>{e.preventDefault();const email=$("#email").value,password=$("#password").value;let r=await sb.auth.signInWithPassword({email,password});if(r.error)r=await sb.auth.signUp({email,password});$("#authMsg").textContent=r.error?r.error.message:"Success.";if(!r.error)setTimeout(()=>location.reload(),700)});$("#googleAuth")&&($("#googleAuth").onclick=()=>sb.auth.signInWithOAuth({provider:"google",options:{redirectTo:location.href}}));$("#searchBtn")&&($("#searchBtn").onclick=()=>{$("#searchDialog")?.showModal();$("#searchInput")?.focus()});$("#searchInput")&&($("#searchInput").oninput=e=>{const q=e.target.value.toLowerCase();$("#searchResults").innerHTML=catalog.filter(x=>(x.title+" "+(x.description||"")+" "+(x.division_key||"")+" "+(x.tags||[]).join(" ")).toLowerCase().includes(q)).map(x=>'<div class="result"><a href="title.html?id='+x.id+'">'+esc(x.title)+'</a></div>').join("")||'<p class="muted">No results.</p>'});
sb.auth.onAuthStateChange(()=>loadUser());load();