const SB_URL="https://cevylpnoexugwgygvtgu.supabase.co",SB_KEY="sb_publishable_AdfM5y6RqvF3tbvEVzDZSg_JuGTQLD-";const sb=window.supabase.createClient(SB_URL,SB_KEY);const $=s=>document.querySelector(s);const esc=v=>String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[m]));let all=[],filter="all",user=null,liveChannels=[],watchRows=[],favoriteChannels=JSON.parse(localStorage.getItem("crplus_favorite_channels")||"[]");
async function init(){const a=await sb.auth.getUser();user=a.data.user;const btn=$("#authBtn");if(user){renderWelcome();btn.textContent="Sign Out";btn.onclick=async()=>{await sb.auth.signOut();location.reload()};await membership();await continueWatching();await loadMyList()}else btn.onclick=()=>location.href="./profile.html";await Promise.all([loadContent(),loadLive()]);$("#searchInput").addEventListener("input",()=>render(filter))}
async function membership(){const r=await sb.rpc("get_my_membership");if(!r.error&&r.data){const m=Array.isArray(r.data)?r.data[0]:r.data;$("#accountTitle").textContent=m.plan_name||m.plan_key||"Universal Membership";$("#accountText").textContent="Signed in · One Account · One Universe"}}
async function loadContent(){const r=await sb.from("crplus_content").select("id,title,slug,description,thumbnail_url,backdrop_url,content_type,duration_seconds,release_at,is_published,is_featured,membership_level,division_key,age_rating,tags,workflow_status,playback_type,video_url").eq("is_published",true).order("release_at",{ascending:false}).limit(100);if(r.error){$("#catalogGrid").innerHTML='<div class="loading">The library is temporarily unavailable.</div>';return}all=r.data||[];render("all");renderFeatured();renderRails()}
async function loadLive(){const r=await sb.from("crplus_live_channels").select("id,name,description,logo_url,is_live,stream_url,channel_key,sort_order").order("sort_order");if(r.error)return;liveChannels=r.data||[];renderLive();setTimeout(loadLive,30000)}
async function loadMyList(){if(!user)return;const r=await sb.from("crplus_my_list").select("content_id,created_at,crplus_content(id,title,description,thumbnail_url,backdrop_url,content_type,division_key,duration_seconds,is_published)").eq("user_id",user.id).order("created_at",{ascending:false}).limit(12);watchRows=r.data||[];renderMyList()}
function renderMyList(){const el=$("#myListGrid"),wrap=$("#myListRail");if(!el||!wrap)return;const rows=watchRows.map(x=>x.crplus_content).filter(x=>x?.is_published);el.innerHTML=rows.length?rows.map(card).join(""):"";wrap.hidden=!rows.length}
function card(x){const img=x.thumbnail_url||x.backdrop_url,target=x.content_type==="show"?"title.html":"watch.html",listed=watchRows.some(w=>w.content_id===x.id);return '<a class="card" href="./'+target+'?id='+encodeURIComponent(x.id)+'"><div class="thumb">'+(img?'<img loading="lazy" src="'+esc(img)+'" alt="">':'<b>CR+</b>')+'</div><div class="cardBody"><h3>'+esc(x.title||"Untitled")+'</h3><div class="meta">'+esc(x.content_type||"title")+' · '+esc(x.division_key||"CrowRules+")+(x.duration_seconds?" · "+Math.round(x.duration_seconds/60)+" min":"")+(listed?' · ✓ My List':'')+'</div><p class="meta">'+esc((x.description||"").slice(0,120))+'</p></div></a>'}
function renderWelcome(){const el=$("#welcome");if(!el||!user)return;el.hidden=false;const name=(user.user_metadata?.full_name||user.user_metadata?.name||user.email||"Member").split("@")[0].split(" ")[0];$("#welcomeTitle").textContent="Welcome back, "+name;$("#welcomeText").textContent="Your CrowRules universe is ready — live TV, your list and your unfinished shows are waiting."}
function toggleFavorite(id,e){e.preventDefault();e.stopPropagation();favoriteChannels=favoriteChannels.includes(id)?favoriteChannels.filter(x=>x!==id):[...favoriteChannels,id];localStorage.setItem("crplus_favorite_channels",JSON.stringify(favoriteChannels));renderLive()}
function renderLive(){const el=$("#liveGrid");if(!el)return;const live=liveChannels.filter(c=>c.is_live).sort((a,b)=>Number(favoriteChannels.includes(b.id))-Number(favoriteChannels.includes(a.id)));el.innerHTML=live.length?live.map(c=>'<div class="liveCard"><a class="liveCardLink" href="./live.html?channel='+encodeURIComponent(c.id)+'"><div class="liveThumb">'+(c.logo_url?'<img src="'+esc(c.logo_url)+'" alt="">':'<span>LIVE</span>')+'</div><div><b>'+esc(c.name)+'</b><small>● LIVE · Watch now</small></div></a><button class="channelStar '+(favoriteChannels.includes(c.id)?"saved":"")+'" onclick="toggleFavorite(''+esc(c.id)+'',event)" aria-label="Favorite channel">'+(favoriteChannels.includes(c.id)?"★":"☆")+'</button></div>').join(""):'<div class="loading">No channels are live right now. Check the TV Guide for upcoming programming.</div>'}
function render(f){filter=f;const q=($("#searchInput")?.value||"").trim().toLowerCase();let rows=f==="all"?all:all.filter(x=>x.content_type===f);if(q)rows=rows.filter(x=>(x.title+" "+(x.description||"")+" "+(x.division_key||"")+" "+(x.tags||[]).join(" ")).toLowerCase().includes(q));$("#catalogGrid").innerHTML=rows.length?rows.map(card).join(""):'<div class="loading">No titles match your search.</div>';$("#resultCount").textContent=rows.length+" title"+(rows.length===1?"":"s")}
function renderFeatured(){const rows=all.filter(x=>x.is_featured).slice(0,8);$("#featuredGrid").innerHTML=rows.length?rows.map(card).join(""):'<div class="loading">Featured programming is coming soon.</div>'}
function renderRails(){const groups=[["SERIES","series"],["FILMS","film"],["SHORTS","short"],["PODCASTS","podcast"],["SPORTS","sports"]];for(const [label,type] of groups){const id="rail-"+type;let el=document.getElementById(id);if(el){const rows=all.filter(x=>x.content_type===type).slice(0,10);el.innerHTML=rows.length?rows.map(card).join(""):'<div class="loading">No '+label.toLowerCase()+' published yet.</div>'}}}
async function continueWatching(){const r=await sb.from("crplus_watch_history").select("content_id,position_seconds,last_watched_at,completed,crplus_content(id,title,description,thumbnail_url,backdrop_url,content_type,division_key,duration_seconds,is_published)").eq("user_id",user.id).eq("completed",false).order("last_watched_at",{ascending:false}).limit(8);if(r.error||!r.data?.length)return;const seen=new Set();const rows=r.data.filter(x=>x.crplus_content?.is_published&&!seen.has(x.content_id)&&seen.add(x.content_id));$("#continueGrid").innerHTML=rows.map(x=>'<a class="card progressCard" href="./watch.html?id='+encodeURIComponent(x.content_id)+'"><div class="thumb">'+(x.crplus_content.thumbnail_url?'<img loading="lazy" src="'+esc(x.crplus_content.thumbnail_url)+'" alt="">':'<b>CR+</b>')+'<span class="resumeBar"><i style="width:'+Math.min(100,(Number(x.position_seconds||0)/Math.max(1,Number(x.crplus_content.duration_seconds||1))*100))+'%"></i></span></div><div class="cardBody"><h3>'+esc(x.crplus_content.title)+'</h3><div class="meta">Resume watching · '+Math.round(Number(x.position_seconds||0)/60)+' min in</div></div></a>').join("");$("#continue").hidden=!rows.length}
document.querySelectorAll(".filter").forEach(b=>b.onclick=()=>{document.querySelectorAll(".filter").forEach(x=>x.classList.remove("active"));b.classList.add("active");render(b.dataset.filter)});init();