const sb=supabase.createClient("https://cevylpnoexugwgygvtgu.supabase.co","sb_publishable_AdfM5y6RqvF3tbvEVzDZSg_JuGTQLD-");const $=id=>document.getElementById(id),esc=v=>String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[m]));let awards=[];
async function init(){const u=await sb.auth.getUser();if(!u.data?.user)return deny();const a=await sb.from("crplus_admins").select("is_active").eq("user_id",u.data.user.id).eq("is_active",true).maybeSingle();if(!a.data)return deny();const r=await sb.from("spectrum_awards").select("id,title,award_year").neq("status","archived").order("award_year",{ascending:false});awards=r.data||[];$("award").innerHTML=awards.map(x=>'<option value="'+x.id+'">'+esc(x.award_year)+' · '+esc(x.title)+'</option>').join("");await load()}
function deny(){ $("certify").disabled=true;$("status").innerHTML='<div class="tvEmpty">Administrator access required.</div>'}
$("award").onchange=load;
async function load(){const awardId=$("award").value;const c=await sb.from("spectrum_voting_config").select("*").eq("award_id",awardId).maybeSingle();const ce=await sb.from("spectrum_ceremonies").select("id,title").eq("award_id",awardId).order("starts_at");$("ceremony").innerHTML='<option value="">No ceremony</option>'+(ce.data||[]).map(x=>'<option value="'+x.id+'">'+esc(x.title)+'</option>').join("");await loadSegments();if(!c.data){$("status").innerHTML='<div class="tvEmpty">No voting configuration.</div>';$("certify").disabled=true;return}$("status").innerHTML='<div class="tvRowCard"><strong>Status: '+esc(c.data.voting_status)+'</strong><p>Certification requires a closed ballot. Ties are blocked.</p></div>';const b=await sb.from("spectrum_ballots").select("category_id,nominee_id,spectrum_categories(name),spectrum_nominees(name)").eq("voting_config_id",c.data.id);const rows=[];(b.data||[]).forEach(x=>{let z=rows.find(q=>q.cat===x.category_id&&q.nom===x.nominee_id);if(z)z.votes++;else rows.push({cat:x.category_id,nom:x.nominee_id,name:x.spectrum_categories?.name,title:x.spectrum_nominees?.name,votes:1})});const groups={};rows.forEach(x=>(groups[x.cat]??=[]).push(x));$("results").innerHTML=Object.values(groups).map(g=>{g.sort((a,b)=>b.votes-a.votes);const tie=g.length>1&&g[1].votes===g[0].votes;return '<article class="tvRowCard"><strong>'+esc(g[0].name)+'</strong><p>'+g.map(x=>esc(x.title)+' — '+x.votes+' vote'+(x.votes===1?"":"s")).join("<br>")+'</p><strong>'+ (tie?'⚠ Tie — certification blocked':'Current leader: '+esc(g[0].title))+'</strong></article>'}).join("")||'<div class="tvEmpty">No votes recorded.</div>';$("certify").disabled=c.data.voting_status!=="closed"||!rows.length||Object.values(groups).some(g=>g.length>1&&g[1].votes===g[0].votes)}
async function loadSegments(){const id=$("ceremony").value;$("reveal").innerHTML='<option value="">No reveal segment</option>';if(!id)return;const r=await sb.from("spectrum_ceremony_segments").select("id,title,segment_type,sort_order").eq("ceremony_id",id).order("sort_order");$("reveal").innerHTML='<option value="">No reveal segment</option>'+(r.data||[]).filter(x=>x.segment_type==="winner_reveal").map(x=>'<option value="'+x.id+'">'+esc(x.title)+'</option>').join("")}
$("ceremony").onchange=loadSegments;
$("certify").onclick=async()=>{const c=await sb.from("spectrum_voting_config").select("id").eq("award_id",$("award").value).single();if(c.error)return alert(c.error.message);if(!confirm("Certify verified vote totals and create the official winner records?"))return;const r=await sb.rpc("spectrum_certify_results",{p_voting_config_id:c.data.id,p_note:$("note").value.trim()||null,p_ceremony_id:$("ceremony").value||null,p_reveal_segment_id:$("reveal").value||null});if(r.error)alert(r.error.message);else{alert("Results certified and routed to the Winners Archive.");$("note").value="";await load()}}
async function init(){const u=await sb.auth.getUser();if(!u.data?.user)return deny();const a=await sb.from("crplus_admins").select("is_active").eq("user_id",u.data.user.id).eq("is_active",true).maybeSingle();if(!a.data)return deny();const [aw]=await Promise.all([sb.from("spectrum_awards").select("id,title,award_year").neq("status","archived").order("award_year",{ascending:false})]);const awards=aw.data||[];$("award").innerHTML=awards.map(x=>'<option value="'+x.id+'">'+esc(x.award_year)+' · '+esc(x.title)+'</option>').join("");if(awards[0])await load()}
function deny(){$("certify").disabled=true;$("results").innerHTML='<div class="tvEmpty">Administrator access required.</div>'}init();